# Generated by Django 5.2.5 on 2025-11-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_ingredient_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
