# Generated by Django 5.2.5 on 2025-11-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_flavor_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
    ]
